import '/database/app_database.dart'; // Adjust the import path as per your project structure

class ProfileController {
  final AppDatabase db;

  const ProfileController(this.db);

  Future<User?> getUser(int userId) async {
    // Assuming 'User' is the data class name generated by Drift for your 'Users' table
    final query = db.select(db.users)..where((tbl) => tbl.id.equals(userId));
    return query
        .getSingleOrNull(); // Fetches a single user by ID or returns null if not found
  }

  // Add more methods as needed for updating user data, handling sign-out, etc.
}
